Enhance DropdownMenu Component to Control Nested Submenu Visibility
mashmatrix/react-lightning-design-system pull request #445
Opened 2024-07-03 08:56 UTC by kosuke-k

## Overview
The DropdownMenu component could not control the opening and closing of nested submenus, and when switching between submenus, the original menu remained open.
When a submenu is switched, the original menu should be closed and the newly clicked menu should be opened.

## What I Did
- Manage the opening and closing of all menus with objects
- Move state management to parent component and pass it to child components in context

2024-07-04 04:33 UTC, stomita requested changes

2024-07-04 04:33 UTC, stomita commented on src/scripts/DropdownMenu.tsx
> +  openSubmenuKey?: string | number;
Is this prop used ?

2024-07-04 04:33 UTC, stomita commented on package.json
> +  "version": "5.6.1",
actually the latest version is 5.6.1, so it would be `5.6.2`.

2024-07-04 04:33 UTC, stomita commented on src/scripts/DropdownMenu.tsx
> +        handleSubmenuOpen(eventKey.toString(), level + 1);
This change requires the `eventKey` to be set for all menu item with submenu to be expanded, which is an destructive one.

2024-07-05 06:16 UTC, kosuke-k commented on package.json
> +  "version": "5.6.1",
Fiexed e8cd424e42c4449865629d10965a3041704f1257

2024-07-05 06:16 UTC, kosuke-k commented on src/scripts/DropdownMenu.tsx
> +  openSubmenuKey?: string | number;
Certainly not being used, so I deleted it.

2024-07-05 06:27 UTC, kosuke-k commented on src/scripts/DropdownMenu.tsx
> +        handleSubmenuOpen(eventKey.toString(), level + 1);
Instead of `eventKey`, I've switched to using `useId` as a reference for an internal key. If you have any concerns or suggestions about this change, please let me know. ab824fcb75fb1b575a1b545977c03550b0305740

2024-07-09 01:33 UTC, stomita approved these changes

2024-07-09 01:33 UTC, merged