Add optional tooltip prop to Tabs component
mashmatrix/react-lightning-design-system pull request #446
Opened 2024-10-01 03:22 UTC by kosuke-k

## Overview
We want to be able to add an arbitrary tooltip to the `Tabs` component using `Popover`.

<img width="429" alt="image" src="https://github.com/user-attachments/assets/cdc91e3d-16bf-4ca7-80bf-b4731cb56a21">

## What I Did
- Add `tooltipText` and `tooltipContent` as prop.
- Tooltip cases added to `Tabs.stories`

2024-10-01 07:32 UTC, stomita requested changes

2024-10-01 07:32 UTC, stomita commented on package.json
> +  "version": "5.6.4",
The version will be updated on publishing package, not required for each PR.

2024-10-01 07:32 UTC, stomita commented on src/scripts/Tabs.tsx
> +    tooltipContent: TooltipContent,
This could be a prop of `tooltip` which is a `ReactNode` type, instead of having multiple properties.

2024-10-01 07:32 UTC, stomita commented on src/scripts/Tabs.tsx
> +            tooltipText ? 'tooltip-enabled' : ''
The `tooltip-enabled` class name should be prefixed with a namespace of `react-slds`, as it may conflicts to application-defined class names.

2024-10-01 07:32 UTC, stomita commented on src/scripts/Tabs.tsx
> +              className='slds-dropdown-trigger tooltip-content'
The `tooltip-content` class name should be prefixed with a namespace of `react-slds`, as it may conflicts to application-defined class names.

2024-10-02 06:10 UTC, kosuke-k commented on src/scripts/Tabs.tsx
> +    tooltipContent: TooltipContent,
Fixed in https://github.com/mashmatrix/react-lightning-design-system/pull/446/commits/f6c257e589e7ec6cb3c6c406c56fa6fca66db87a

2024-10-02 06:10 UTC, kosuke-k commented on package.json
> +  "version": "5.6.4",
Fixed in https://github.com/mashmatrix/react-lightning-design-system/pull/446/commits/f6c257e589e7ec6cb3c6c406c56fa6fca66db87a

2024-10-02 06:10 UTC, kosuke-k commented on src/scripts/Tabs.tsx
> +            tooltipText ? 'tooltip-enabled' : ''
Fixed in https://github.com/mashmatrix/react-lightning-design-system/pull/446/commits/f6c257e589e7ec6cb3c6c406c56fa6fca66db87a

2024-10-02 06:12 UTC, kosuke-k commented on src/scripts/Tabs.tsx
> +              className='slds-dropdown-trigger tooltip-content'
Fixed in https://github.com/mashmatrix/react-lightning-design-system/pull/446/commits/fa6b7bacd922ca95c883df5a0bbf4b56a31a0536.
Is this the intended content?

2024-10-02 08:53 UTC, stomita requested changes

2024-10-02 08:53 UTC, stomita commented on src/scripts/Tabs.tsx
> +      ['.slds-popover_tooltip', '{ left: -1rem !important; }'],
This is overriding the style of the class defined in Salesforce Lightning Design System, and it will affects to other stylings. It should be narrowed by a custom class name.

2024-10-02 10:21 UTC, stomita requested changes

2024-10-02 10:21 UTC, stomita commented on stories/Tabs.stories.tsx
> +      />
If it is always assumed that showing an `info` icon and popover for the tooltip, it is more natural to embed these buttons and popover container to inside of the `Tab` component, and just accept the content of popover body of tooltip as a ReactNode property.

2024-10-04 02:09 UTC, stomita requested changes

2024-10-04 02:09 UTC, stomita commented on src/scripts/Popover.tsx
> +      ['.slds-popover_tooltip a', '{ color: white; }'],
This overrides standard SLDS style, so scoping by class name should be required

2024-10-07 01:48 UTC, stomita approved these changes

2024-10-07 01:48 UTC, merged